<a href="https://colab.research.google.com/github/sevcikoleksandr233/machine-learning/blob/main/%D0%A8%D0%B5%D0%B2%D1%87%D0%B8%D0%BA_%D0%BF%D1%80_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''1. Завантажте вбудований датасет load_breast_cancer з бібліотеки
sklearn.datasets.'''
'''2. Проведіть попередній аналіз даних:
            1. Перегляньте перші кілька рядків.
            2. Перевірте назви стовпців та типи даних.
            3. Перевірте наявність пропущених значень.
            4. Досліджуйте розмір даних.'''

import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target
print(df.head())
print(df.info())

# Перевіримо наявність пропущених значень
print(df.isnull().sum())

# Дослідимо розмір даних
print(df.shape)


   mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0             

In [ ]:
'''2. Побудова і налаштування моделей:
              1. Розділіть дані на навчальний і тестовий набори.
              2. Побудуйте три моделі класифікації (на власний вибір),
              наприклад:
              1. Логістична регресія.
              2. Дерево рішень.
              3. Випадковий ліс (Random Forest).'''

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

X = df.drop('target', axis=1)
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Логістична регресія
log_reg = LogisticRegression(max_iter=10000)
log_reg.fit(X_train, y_train)
y_pred_log_reg = log_reg.predict(X_test)

# Дерево рішень
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)
y_pred_tree = tree_clf.predict(X_test)

# Випадковий ліс
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)
y_pred_rf = rf_clf.predict(X_test)


In [ ]:
'''3. Підберіть оптимальні параметри для кожної моделі за допомогою
GridSearchCV (можна вибрати інший оптимізатор).'''

# Налаштування параметрів для логістичної регресії
param_grid_log = {'C': [0.1, 1, 10]}
grid_log_reg = GridSearchCV(LogisticRegression(max_iter=10000), param_grid_log, cv=5)
grid_log_reg.fit(X_train, y_train)

# Налаштування параметрів для дерева рішень
param_grid_tree = {'max_depth': [3, 5, 10]}
grid_tree_clf = GridSearchCV(DecisionTreeClassifier(), param_grid_tree, cv=5)
grid_tree_clf.fit(X_train, y_train)

# Налаштування параметрів для випадкового лісу
param_grid_rf = {'n_estimators': [50, 100, 200]}
grid_rf_clf = GridSearchCV(RandomForestClassifier(), param_grid_rf, cv=5)
grid_rf_clf.fit(X_train, y_train)


GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'n_estimators': [50, 100, 200]})

In [ ]:
'''3.Оцініть моделі. Виведіть точність (accuracy) – обов’язково, матрицю
помилок (confusion matrix) – за вибором та звіт про класифікацію (classification report) для кожної моделі.'''
# Оцінка Логістичної регресії
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_log_reg))
print(confusion_matrix(y_test, y_pred_log_reg))
print(classification_report(y_test, y_pred_log_reg))

# Оцінка Дерева рішень
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_tree))
print(confusion_matrix(y_test, y_pred_tree))
print(classification_report(y_test, y_pred_tree))

# Оцінка Випадкового лісу
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))


Logistic Regression Accuracy: 0.956140350877193
[[39  4]
 [ 1 70]]
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

Decision Tree Accuracy: 0.9385964912280702
[[39  4]
 [ 3 68]]
              precision    recall  f1-score   support

           0       0.93      0.91      0.92        43
           1       0.94      0.96      0.95        71

    accuracy                           0.94       114
   macro avg       0.94      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114

Random Forest Accuracy: 0.9649122807017544
[[40  3]
 [ 1 70]]
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97   

In [ ]:
'''4. Прогнозування і висновки
        1. Оберіть найкращу модель на основі метрик продуктивності.
        2. Зробіть прогноз на тестовій вибірці.
        3. Виведіть результати прогнозування.'''

# Використовуємо найкращу модель (Random Forest) для прогнозування
y_pred_best = grid_rf_clf.best_estimator_.predict(X_test)

# Виводимо результати прогнозування
print("Results of prediction using the best model (Random Forest):", y_pred_best)
print("Accuracy of the best model (Random Forest):", accuracy_score(y_test, y_pred_best))


Results of prediction using the best model (Random Forest): [1 0 0 1 1 0 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0
 1 0 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 1 0 0 1 1 1 0 0 1 1 0 0 1 0
 1 1 1 1 1 1 0 1 1 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 1 1 0
 1 1 0]
Accuracy of the best model (Random Forest): 0.9649122807017544


In [ ]:
'''Завдання 2. Продовжуємо працювати з датасетом titanic.csv
Завантажуємо, проводимо попередній аналіз даних (лр 2).'''
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')
import os
file_path = '/content/drive/My Drive/titanic.csv'
df = pd.read_csv(file_path)

df.head(5)

Mounted at /content/drive


PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [ ]:
# Перевіримо типи даних і наявність пропущених значень
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Name         418 non-null    object 
 4   Sex          418 non-null    object 
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64  
 7   Parch        418 non-null    int64  
 8   Ticket       418 non-null    object 
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object 
 11  Embarked     418 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB
None
       PassengerId    Survived      Pclass         Age       SibSp  \
count   418.000000  418.000000  418.000000  332.000000  418.000000   
mean   1100.500000    0.363636    2.265550   30.272590    0.447368   
std     120.810458    0.48162

In [ ]:
'''2. Попередня обробка даних'''
# Видаляємо непотрібні стовпці, наприклад, 'Name', 'Ticket', 'Cabin'
df = df.drop(['Name', 'Ticket', 'Cabin'], axis=1)

# Заповнюємо пропущені значення в колонках 'Age' та 'Embarked'
df['Age'].fillna(df['Age'].median(), inplace=True)
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Перетворюємо категоріальні дані на числові (наприклад, 'Sex' і 'Embarked')
df['Sex'] = df['Sex'].map({'male': 0, 'female': 1})
df = pd.get_dummies(df, columns=['Embarked'], drop_first=True)

# Перевіряємо результат після обробки
print(df.head())


   PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch     Fare  \
0          892         0       3    0  34.5      0      0   7.8292   
1          893         1       3    1  47.0      1      0   7.0000   
2          894         0       2    0  62.0      0      0   9.6875   
3          895         0       3    0  27.0      0      0   8.6625   
4          896         1       3    1  22.0      1      1  12.2875   

   Embarked_Q  Embarked_S  
0        True       False  
1       False        True  
2        True       False  
3       False        True  
4       False        True  


In [ ]:
'''3. Побудова і налаштування моделей'''
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.impute import SimpleImputer

# Розділяємо дані на навчальний і тестовий набори
imputer = SimpleImputer(strategy='mean')

# Застосовуємо імпутер до числових колонок
X_train = imputer.fit_transform(X_train)
X_test = imputer.transform(X_test)

# Логістична регресія
log_reg = LogisticRegression(max_iter=10000)
log_reg.fit(X_train, y_train)
y_pred_log_reg = log_reg.predict(X_test)

# Дерево рішень
tree_clf = DecisionTreeClassifier()
tree_clf.fit(X_train, y_train)
y_pred_tree = tree_clf.predict(X_test)

# Випадковий ліс
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, y_train)
y_pred_rf = rf_clf.predict(X_test)


In [ ]:
'''4. Налаштування параметрів за допомогою GridSearchCV'''
# Налаштування параметрів для логістичної регресії
param_grid_log = {'C': [0.1, 1, 10]}
grid_log_reg = GridSearchCV(LogisticRegression(max_iter=10000), param_grid_log, cv=5)
grid_log_reg.fit(X_train, y_train)

# Налаштування параметрів для дерева рішень
param_grid_tree = {'max_depth': [3, 5, 10]}
grid_tree_clf = GridSearchCV(DecisionTreeClassifier(), param_grid_tree, cv=5)
grid_tree_clf.fit(X_train, y_train)

# Налаштування параметрів для випадкового лісу
param_grid_rf = {'n_estimators': [50, 100, 200]}
grid_rf_clf = GridSearchCV(RandomForestClassifier(), param_grid_rf, cv=5)
grid_rf_clf.fit(X_train, y_train)


GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'n_estimators': [50, 100, 200]})

In [ ]:
'''5. Оцінка моделей'''
# Оцінка Логістичної регресії
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_log_reg))
print(confusion_matrix(y_test, y_pred_log_reg))
print(classification_report(y_test, y_pred_log_reg))

# Оцінка Дерева рішень
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_tree))
print(confusion_matrix(y_test, y_pred_tree))
print(classification_report(y_test, y_pred_tree))

# Оцінка Випадкового лісу
print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print(confusion_matrix(y_test, y_pred_rf))
print(classification_report(y_test, y_pred_rf))


Logistic Regression Accuracy: 0.956140350877193
[[39  4]
 [ 1 70]]
              precision    recall  f1-score   support

           0       0.97      0.91      0.94        43
           1       0.95      0.99      0.97        71

    accuracy                           0.96       114
   macro avg       0.96      0.95      0.95       114
weighted avg       0.96      0.96      0.96       114

Decision Tree Accuracy: 0.9298245614035088
[[40  3]
 [ 5 66]]
              precision    recall  f1-score   support

           0       0.89      0.93      0.91        43
           1       0.96      0.93      0.94        71

    accuracy                           0.93       114
   macro avg       0.92      0.93      0.93       114
weighted avg       0.93      0.93      0.93       114

Random Forest Accuracy: 0.9649122807017544
[[40  3]
 [ 1 70]]
              precision    recall  f1-score   support

           0       0.98      0.93      0.95        43
           1       0.96      0.99      0.97   

In [ ]:
'''6. Прогнозування для 10 випадків'''
# Вибираємо найкращу модель
best_model = grid_rf_clf.best_estimator_ if accuracy_score(y_test, y_pred_rf) > max(accuracy_score(y_test, y_pred_log_reg), accuracy_score(y_test, y_pred_tree)) else grid_log_reg.best_estimator_ if accuracy_score(y_test, y_pred_log_reg) > accuracy_score(y_test, y_pred_tree) else grid_tree_clf.best_estimator_

# Прогнозуємо для 10 випадків
sample_data = X_test[:10]
y_pred_best = best_model.predict(sample_data)

# Виведемо результати прогнозування
print("Predictions for 10 cases:", y_pred_best)


Predictions for 10 cases: [1 0 0 1 1 0 0 0 0 1]
