<a href="https://colab.research.google.com/github/sevcikoleksandr233/machine-learning/blob/main/%D0%A8%D0%B5%D0%B2%D1%87%D0%B8%D0%BA_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Завдання 1
# Створіть одновимірний масив (вектор) з сумами кожного числа та його
# попереднього, починаючи з 1, та виведіть його значення.

import numpy as np

n = 10
arr = np.arange(1, n + 1)
result = np.zeros(n, dtype=int)

for i in range(n):
    if i == 0:
        result[i] = arr[i]
    else:
        result[i] = arr[i] + arr[i - 1]

print(result)


[ 1  3  5  7  9 11 13 15 17 19]


In [2]:
# Завдання 2
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями
# випадкових дійсних чисел від 1 до 10.

import numpy as np

rows, cols = 3, 3
matrix = np.random.uniform(1, 10, size=(rows, cols))

print(matrix)


[[6.46918163 1.42327097 8.09877526]
 [9.4426117  5.76230773 9.79982857]
 [6.47397944 3.70079024 1.6227061 ]]


In [3]:
# Завдання 3
# Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
# 1 до 100 та виведіть мін значення

import numpy as np

rows, cols = 3, 3
matrix = np.random.randint(1, 101, size=(rows, cols))
min_value = np.min(matrix)

print("Матриця:")
print(matrix)
print("Мінімальне значення:", min_value)


Матриця:
[[34 91 59]
 [46 46 58]
 [61  6 40]]
Мінімальне значення: 6


In [4]:
# Завдання 4
# Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в
# діапазоні від 0 до 1 та знайдіть кількість елементів, що більше 0.5.

import numpy as np

matrix = np.random.uniform(0, 1, size=(4, 4))
count = np.sum(matrix > 0.5)

print("Матриця:")
print(matrix)
print("Кількість елементів, що більше 0.5:", count)


Матриця:
[[0.40214051 0.49278927 0.56927142 0.03432298]
 [0.74498962 0.94373413 0.4195586  0.76862512]
 [0.37121404 0.80488147 0.4611621  0.68587501]
 [0.32277653 0.93721724 0.92932285 0.5844    ]]
Кількість елементів, що більше 0.5: 9


In [5]:
# Завдання 5
# Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими
# числами від -10 до 10 та виконайте на них поелементні операції додавання, віднімання
# та множення.

import numpy as np

array1 = np.random.randint(-10, 11, size=4)
array2 = np.random.randint(-10, 11, size=4)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Масив 1:")
print(array1)
print("Масив 2:")
print(array2)
print("Додавання:")
print(addition)
print("Віднімання:")
print(subtraction)
print("Множення:")
print(multiplication)


Масив 1:
[-6 -3 -1  9]
Масив 2:
[ 7 -8 -3 -9]
Додавання:
[  1 -11  -4   0]
Віднімання:
[-13   5   2  18]
Множення:
[-42  24   3 -81]


In [6]:
# Завдання 6
# Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 20 та
# знайдіть їх добуток.

import numpy as np

matrix1 = np.random.randint(1, 21, size=(3, 3))
matrix2 = np.random.randint(1, 21, size=(3, 3))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)


Матриця 1:
[[16  8 15]
 [ 3  7 14]
 [ 3  6 14]]
Матриця 2:
[[ 5  4  6]
 [ 8  3 18]
 [ 5 14  1]]
Добуток матриць:
[[219 298 255]
 [141 229 158]
 [133 226 140]]


In [7]:
# Завдання 7
# Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами
# в діапазоні від 1 до 4 та перемножте їх між собою.

import numpy as np

matrix1 = np.random.randint(1, 5, size=(2, 3))
matrix2 = np.random.randint(1, 5, size=(3, 3))

product = np.dot(matrix1, matrix2)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток матриць:")
print(product)


Матриця 1:
[[2 2 2]
 [4 1 1]]
Матриця 2:
[[1 4 4]
 [1 3 2]
 [3 4 4]]
Добуток матриць:
[[10 22 20]
 [ 8 23 22]]


In [8]:
# Завдання 8
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
# від 1 до 7 та знайдіть її обернену матрицю.

import numpy as np

matrix = np.random.randint(1, 8, size=(3, 3))

try:
    inverse_matrix = np.linalg.inv(matrix)
    print("Матриця:")
    print(matrix)
    print("Обернена матриця:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("Матриця не є оберненою (можливо, її детермінант дорівнює нулю).")


Матриця не є оберненою (можливо, її детермінант дорівнює нулю).


In [9]:
# Завдання 9
# Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні
# від 0 до 1 та транспонуйте її.

import numpy as np

matrix = np.random.randint(0, 2, size=(4, 4))
transposed_matrix = np.transpose(matrix)

print("Матриця:")
print(matrix)
print("Транспонована матриця:")
print(transposed_matrix)


Матриця:
[[0 1 0 0]
 [0 1 1 1]
 [0 0 0 1]
 [0 1 1 0]]
Транспонована матриця:
[[0 0 0 0]
 [1 1 0 1]
 [0 1 0 1]
 [0 1 1 0]]


In [10]:
# Завдання 10
# Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
# випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
# від 0 до 1, і знайдіть добуток матриці на вектор

import numpy as np

matrix = np.random.uniform(0, 1, size=(3, 4))
vector = np.random.uniform(0, 1, size=(4, 1))

product = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Добуток матриці на вектор:")
print(product)


Матриця:
[[0.34988616 0.14638968 0.88364756 0.81144744]
 [0.10387043 0.92479389 0.91274641 0.48874947]
 [0.54928576 0.18642292 0.89843247 0.68915838]]
Вектор:
[[0.58639718]
 [0.87245824]
 [0.04309355]
 [0.4588769 ]]
Добуток матриці на вектор:
[[0.74332515]
 [1.1313627 ]
 [0.83970135]]


In [11]:
# Завдання 11
# Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
# випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами
# від 0 до 1, і знайдіть добуток матриці на вектор

import numpy as np

matrix = np.random.uniform(0, 1, size=(2, 3))
vector = np.random.uniform(0, 1, size=(3, 1))

product = np.dot(matrix, vector)

print("Матриця:")
print(matrix)
print("Вектор:")
print(vector)
print("Добуток матриці на вектор:")
print(product)


Матриця:
[[0.997011   0.90871201 0.02029798]
 [0.9942429  0.04777968 0.85739701]]
Вектор:
[[0.31077814]
 [0.88328477]
 [0.38199967]]
Добуток матриці на вектор:
[[1.12025453]
 [0.6787174 ]]


In [12]:
# Завдання 12
# Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 5 та знайдіть добуток елементів діагоналі другої матриці.

import numpy as np

matrix1 = np.random.randint(1, 6, size=(3, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

diagonal_elements = np.diag(matrix2)
product_of_diagonal = np.prod(diagonal_elements)

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Добуток елементів діагоналі другої матриці:")
print(product_of_diagonal)


Матриця 1:
[[1 3 5]
 [5 1 1]
 [1 5 1]]
Матриця 2:
[[1 4 2]
 [2 5 2]
 [1 5 2]]
Добуток елементів діагоналі другої матриці:
10


In [13]:
# Завдання 13
# Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в
# діапазоні від 1 до 5 та знайдіть різницю їх елементів.

import numpy as np

matrix1 = np.random.randint(1, 6, size=(4, 4))
matrix2 = np.random.randint(1, 6, size=(4, 4))

difference = matrix1 - matrix2

print("Матриця 1:")
print(matrix1)
print("Матриця 2:")
print(matrix2)
print("Різниця матриць:")
print(difference)


Матриця 1:
[[1 5 2 1]
 [5 4 1 2]
 [3 3 3 4]
 [1 1 5 3]]
Матриця 2:
[[5 5 4 5]
 [5 5 3 4]
 [5 3 3 1]
 [3 4 5 1]]
Різниця матриць:
[[-4  0 -2 -4]
 [ 0 -1 -2 -2]
 [-2  0  0  3]
 [-2 -3  0  2]]


In [14]:
# Завдання 14
# Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
# від 1 до 10 та знайдіть найменший елемент матриці.

import numpy as np

matrix = np.random.randint(1, 11, size=(3, 3))
min_element = np.min(matrix)

print("Матриця:")
print(matrix)
print("Найменший елемент матриці:")
print(min_element)


Матриця:
[[5 3 1]
 [2 7 8]
 [1 6 4]]
Найменший елемент матриці:
1


In [15]:
# Завдання 15
# Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
# діапазоні від -2 до 2 та знайдіть вектор-стовпчик, що містить кількість ненульових
# елементів в кожному рядку матриці.

import numpy as np

matrix = np.random.uniform(-2, 2, size=(3, 3))
non_zero_counts = np.sum(matrix != 0, axis=1)

print("Матриця:")
print(matrix)
print("Кількість ненульових елементів в кожному рядку:")
print(non_zero_counts)


Матриця:
[[-0.72517083 -1.38184832 -0.22481257]
 [ 0.58221953  1.76125544 -1.45931108]
 [ 1.61461821  1.91304068  0.91845767]]
Кількість ненульових елементів в кожному рядку:
[3 3 3]


In [ ]:
'''
Під час виконання лабораторної роботи було вивчено можливості бібліотеки
NumPy для опрацювання масивів і матриць. Було створено різноманітні масиви,
заповнені випадковими числами, а також проведено операції додавання, віднімання,
множення, транспонування, обчислення оберненої матриці, добутку матриць та інші
математичні дії. Використання бібліотеки NumPy забезпечує ефективну роботу з
великими наборами даних і дозволяє виконувати обчислення з високою продуктивністю.
Завдання наочно показали основні можливості бібліотеки для роботи з масивами і
матрицями.'''