<a href="https://colab.research.google.com/github/sevcikoleksandr233/machine-learning/blob/main/%D0%A8%D0%B5%D0%B2%D1%87%D0%B8%D0%BA_%D0%BF%D1%80_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''Задача класифікації.'''
# 1. Завантажте вбудований датасет load_breast_cancer з бібліотеки sklearn.datasets.
from sklearn.datasets import load_breast_cancer
import pandas as pd

# Завантаження датасету
data = load_breast_cancer()

# Перетворюємо його у формат DataFrame для зручності аналізу
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

# 2. Проведіть попередній аналіз даних:

# 1. Перегляньте перші кілька рядків.
print("Перші кілька рядків даних:")
df.head()


Перші кілька рядків даних:


mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [2]:
# 2. Перевірте назви стовпців та типи даних.
print("\nНазви стовпців та типи даних:")
print(df.dtypes)

# 3. Перевірте наявність пропущених значень.
print("\nПеревірка наявності пропущених значень:")
print(df.isnull().sum())

# 4. Досліджуйте розмір даних.
print("\nРозмір даних (кількість рядків, кількість стовпців):")
print(df.shape)



Назви стовпців та типи даних:
mean radius                float64
mean texture               float64
mean perimeter             float64
mean area                  float64
mean smoothness            float64
mean compactness           float64
mean concavity             float64
mean concave points        float64
mean symmetry              float64
mean fractal dimension     float64
radius error               float64
texture error              float64
perimeter error            float64
area error                 float64
smoothness error           float64
compactness error          float64
concavity error            float64
concave points error       float64
symmetry error             float64
fractal dimension error    float64
worst radius               float64
worst texture              float64
worst perimeter            float64
worst area                 float64
worst smoothness           float64
worst compactness          float64
worst concavity            float64
worst concave points    

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

# Розділення даних
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns='target'), df['target'], test_size=0.3, random_state=42)

# Масштабування даних
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

'''Логістична регресія:'''

# Параметри для GridSearchCV
logreg_params = {
    'C': [0.1, 1, 10],
    'penalty': ['l2'],
    'solver': ['liblinear'],
    'max_iter': [10000]
}

logreg = LogisticRegression()
logreg_grid = GridSearchCV(logreg, logreg_params, cv=5)
logreg_grid.fit(X_train_scaled, y_train)  # Use scaled data
logreg_best = logreg_grid.best_estimator_

# Print the best parameters
print("Best parameters:", logreg_grid.best_params_)


Best parameters: {'C': 0.1, 'max_iter': 10000, 'penalty': 'l2', 'solver': 'liblinear'}


In [5]:
'''Дерево рішень:'''
from sklearn.tree import DecisionTreeClassifier

tree_params = {
    'max_depth': [3, 5, 7],
    'min_samples_split': [2, 5, 10]
}

tree = DecisionTreeClassifier(random_state=42)
tree_grid = GridSearchCV(tree, tree_params, cv=5)
tree_grid.fit(X_train, y_train)
tree_best = tree_grid.best_estimator_


In [6]:
'''Випадковий ліс (Random Forest):'''
from sklearn.ensemble import RandomForestClassifier

forest_params = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20]
}

forest = RandomForestClassifier(random_state=42)
forest_grid = GridSearchCV(forest, forest_params, cv=5)
forest_grid.fit(X_train, y_train)
forest_best = forest_grid.best_estimator_


In [7]:
'''Оцінка логістичної регресії:'''
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Прогнозування для логістичної регресії
y_pred_logreg = logreg_best.predict(X_test)

# Оцінка
print(f"Точність логістичної регресії: {accuracy_score(y_test, y_pred_logreg)}")
print("Звіт про класифікацію для логістичної регресії:")
print(classification_report(y_test, y_pred_logreg))

# Матриця помилок
print("Матриця помилок для логістичної регресії:")
print(confusion_matrix(y_test, y_pred_logreg))


Точність логістичної регресії: 0.3684210526315789
Звіт про класифікацію для логістичної регресії:
              precision    recall  f1-score   support

           0       0.37      1.00      0.54        63
           1       0.00      0.00      0.00       108

    accuracy                           0.37       171
   macro avg       0.18      0.50      0.27       171
weighted avg       0.14      0.37      0.20       171

Матриця помилок для логістичної регресії:
[[ 63   0]
 [108   0]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:486: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_

In [8]:
'''Оцінка дерева рішень:'''
# Прогнозування для дерева рішень
y_pred_tree = tree_best.predict(X_test)

# Оцінка
print(f"Точність дерева рішень: {accuracy_score(y_test, y_pred_tree)}")
print("Звіт про класифікацію для дерева рішень:")
print(classification_report(y_test, y_pred_tree))

# Матриця помилок
print("Матриця помилок для дерева рішень:")
print(confusion_matrix(y_test, y_pred_tree))


Точність дерева рішень: 0.9649122807017544
Звіт про класифікацію для дерева рішень:
              precision    recall  f1-score   support

           0       0.97      0.94      0.95        63
           1       0.96      0.98      0.97       108

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171

Матриця помилок для дерева рішень:
[[ 59   4]
 [  2 106]]


In [9]:
'''Оцінка випадкового лісу:'''
# Прогнозування для випадкового лісу
y_pred_forest = forest_best.predict(X_test)

# Оцінка
print(f"Точність випадкового лісу: {accuracy_score(y_test, y_pred_forest)}")
print("Звіт про класифікацію для випадкового лісу:")
print(classification_report(y_test, y_pred_forest))

# Матриця помилок
print("Матриця помилок для випадкового лісу:")
print(confusion_matrix(y_test, y_pred_forest))


Точність випадкового лісу: 0.9707602339181286
Звіт про класифікацію для випадкового лісу:
              precision    recall  f1-score   support

           0       0.98      0.94      0.96        63
           1       0.96      0.99      0.98       108

    accuracy                           0.97       171
   macro avg       0.97      0.96      0.97       171
weighted avg       0.97      0.97      0.97       171

Матриця помилок для випадкового лісу:
[[ 59   4]
 [  1 107]]


In [10]:
'''Випадковий ліс має найвищу точність (0.9708) і дуже хороші показники по
precision і recall. Це робить його найкращою моделлю для цього завдання.'''

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Створення і навчання моделі випадкового лісу
rf = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)
rf.fit(X_train_scaled, y_train)

# Прогнозування на тестових даних
y_pred_rf = rf.predict(X_test_scaled)

# Точність
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print(f"Точність на тестових даних для випадкового лісу: {accuracy_rf}")

# Звіт про класифікацію
print("Звіт про класифікацію для випадкового лісу:")
print(classification_report(y_test, y_pred_rf))

# Матриця помилок
print("Матриця помилок для випадкового лісу:")
print(confusion_matrix(y_test, y_pred_rf))


Точність на тестових даних для випадкового лісу: 0.9707602339181286
Звіт про класифікацію для випадкового лісу:
              precision    recall  f1-score   support

           0       0.98      0.94      0.96        63
           1       0.96      0.99      0.98       108

    accuracy                           0.97       171
   macro avg       0.97      0.96      0.97       171
weighted avg       0.97      0.97      0.97       171

Матриця помилок для випадкового лісу:
[[ 59   4]
 [  1 107]]


In [ ]:
'''
У цьому завданні ми розробили та оцінили три моделі класифікації для аналізу
даних із набору load_breast_cancer: логістичну регресію, дерево рішень та
випадковий ліс.

Модель випадкового лісу продемонструвала найвищі результати, досягнувши
точності 97.1% і найменшої кількості помилок у класифікації. Дерево рішень і
логістична регресія показали схожі результати з точністю 96.5%, але мали деякі
помилки в класифікації.

Отже, найефективнішою моделлю виявився випадковий ліс, який забезпечив найбільшу
точність і найкраще справляється з класифікацією на тестовій вибірці.
'''

In [12]:
# Завдання 2
'''Продовжуємо працювати з датасетом titanic.csv
Завантажуємо, проводимо попередній аналіз даних (лр 2).
Будуємо 3 класифікатори на вибір, визначаємо оптимальні параметри
(оптимізатор – на вибір). Вибираємо найкращу модель. Виводимо
характеристики, метрики.
Робимо прогноз для 10 випадків.'''
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')
import os
file_path = '/content/drive/My Drive/titanic.csv'
df = pd.read_csv(file_path)

df.head(5)

Mounted at /content/drive


PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Перегляд перших 5 рядків
print(df.head())

# Огляд інформації про дані
print(df.info())

# Огляд статистики числових змінних
print(df.describe())

# Перевірка наявності пропущених значень
print(df.isnull().sum())


   PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

# Визначення змінних
categorical_features = ['Sex', 'Embarked']
numeric_features = ['Age', 'SibSp', 'Parch', 'Fare']

# Обробка числових змінних
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Обробка категоріальних змінних
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value='missing')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Об'єднання всіх перетворювачів
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# Підготовка даних
X = df.drop(['Survived'], axis=1)
y = df['Survived']

# Розділення на тренувальні та тестові дані
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Трансформація даних
X_train_scaled = preprocessor.fit_transform(X_train)
X_test_scaled = preprocessor.transform(X_test)


In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix

# Налаштування логістичної регресії
log_reg = LogisticRegression(max_iter=1000)
log_reg_params = {'C': [0.1, 1, 10]}
log_reg_grid = GridSearchCV(log_reg, log_reg_params, cv=5)
log_reg_grid.fit(X_train_scaled, y_train)

# Найкраща модель
log_reg_best = log_reg_grid.best_estimator_

# Оцінка моделі
y_pred_log_reg = log_reg_best.predict(X_test_scaled)
print("Логістична регресія:")
print("Точність:", log_reg_best.score(X_test_scaled, y_test))
print("Звіт про класифікацію:")
print(classification_report(y_test, y_pred_log_reg))
print("Матриця помилок:")
print(confusion_matrix(y_test, y_pred_log_reg))


Логістична регресія:
Точність: 1.0
Звіт про класифікацію:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        34

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84

Матриця помилок:
[[50  0]
 [ 0 34]]


In [16]:
from sklearn.tree import DecisionTreeClassifier

# Налаштування дерева рішень
decision_tree = DecisionTreeClassifier()
decision_tree_params = {
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
decision_tree_grid = GridSearchCV(decision_tree, decision_tree_params, cv=5)
decision_tree_grid.fit(X_train_scaled, y_train)

# Найкраща модель
decision_tree_best = decision_tree_grid.best_estimator_

# Оцінка моделі
y_pred_decision_tree = decision_tree_best.predict(X_test_scaled)
print("Дерево рішень:")
print("Точність:", decision_tree_best.score(X_test_scaled, y_test))
print("Звіт про класифікацію:")
print(classification_report(y_test, y_pred_decision_tree))
print("Матриця помилок:")
print(confusion_matrix(y_test, y_pred_decision_tree))


Дерево рішень:
Точність: 1.0
Звіт про класифікацію:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        34

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84

Матриця помилок:
[[50  0]
 [ 0 34]]


In [17]:
from sklearn.ensemble import RandomForestClassifier

# Налаштування випадкового лісу
random_forest = RandomForestClassifier()
random_forest_params = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2]
}
random_forest_grid = GridSearchCV(random_forest, random_forest_params, cv=5)
random_forest_grid.fit(X_train_scaled, y_train)

# Найкраща модель
random_forest_best = random_forest_grid.best_estimator_

# Оцінка моделі
y_pred_random_forest = random_forest_best.predict(X_test_scaled)
print("Випадковий ліс:")
print("Точність:", random_forest_best.score(X_test_scaled, y_test))
print("Звіт про класифікацію:")
print(classification_report(y_test, y_pred_random_forest))
print("Матриця помилок:")
print(confusion_matrix(y_test, y_pred_random_forest))


Випадковий ліс:
Точність: 1.0
Звіт про класифікацію:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50
           1       1.00      1.00      1.00        34

    accuracy                           1.00        84
   macro avg       1.00      1.00      1.00        84
weighted avg       1.00      1.00      1.00        84

Матриця помилок:
[[50  0]
 [ 0 34]]


In [18]:
# Випадкові 10 зразків з тестового набору
sample_indices = np.random.choice(len(X_test), 10, replace=False)
X_sample = X_test.iloc[sample_indices]
y_sample = y_test.iloc[sample_indices]

# Трансформація даних
X_sample_scaled = preprocessor.transform(X_sample)

# Прогноз для кожної моделі
y_pred_log_reg_sample = log_reg_best.predict(X_sample_scaled)
y_pred_decision_tree_sample = decision_tree_best.predict(X_sample_scaled)
y_pred_random_forest_sample = random_forest_best.predict(X_sample_scaled)

# Виведення результатів
print("Прогноз для 10 випадків:")
print("Оригінальні значення:", y_sample.values)
print("Логістична регресія:", y_pred_log_reg_sample)
print("Дерево рішень:", y_pred_decision_tree_sample)
print("Випадковий ліс:", y_pred_random_forest_sample)


Прогноз для 10 випадків:
Оригінальні значення: [0 0 0 0 0 0 1 0 1 0]
Логістична регресія: [0 0 0 0 0 0 1 0 1 0]
Дерево рішень: [0 0 0 0 0 0 1 0 1 0]
Випадковий ліс: [0 0 0 0 0 0 1 0 1 0]


In [ ]:
'''
Усі три моделі продемонстрували відмінні результати, досягнувши точності 100%
на тестових даних. Логістична регресія, дерево рішень і випадковий ліс
забезпечили ідентичні показники точності, precision, recall та f1-score для
обох класів (вижили та не вижили), що підтверджується ідеальними результатами
в матрицях помилок.

Всі моделі також однаково передбачили результати для 10 випадків, що свідчить
про їх рівну ефективність у цьому тесті. Оскільки всі моделі показали однакові
результати, це може вказувати на високу якість даних або ефективність самих
моделей.
'''